POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
  "name": "prueba",
  "email": "rp@hm.com",
  "password": "123456"

}

###

POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
  "name": "pueba2",
  "email": "rp2@hm.com",
  "password": "1234567"

}
###
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3ODIxMDU0MjIsImV4cCI6MTc4MjEwNTQ4Mn0.BOx2Zxs4CI1rxrcqb-Fc9QX9EzkBprRMMnfo6ygSvdI